import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../../components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>炭火焼き鳥や</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >

        <main className={styles.main}>
          <Image src="menu.png" className={styles.menu} alt="炭火焼き鳥メニュー" /></img>
          <h1>ようこそ 炭火焼き鳥へ</h1>
          <p>当店自慢の焼き鳥メニューをご覧ください。</p>
        </main>
        <footer className={styles.footer}>
        </footer>
      </div>
    </>
  );
}
